[package]
name = "confetti_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.1"
# bevy-inspector-egui = "0.25.2"
bevy_rapier2d = { version = "*", features = [ "simd-stable", "debug-render-2d" ] }
rand = "0.8.5"
xcap = "0.0.10"

[build-dependencies]
embed-resource = "1.6.3"
