[package]
name = "confetti_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bevy = "0.14.1"
bevy_rapier2d = { version = "*", features = [ "simd-stable", "debug-render-2d" ] }
directories = "5.0.1"
rand = "0.8.5"
serde = "1.0.206"
serde_json = "1.0.124"
xcap = "0.0.10"
